<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\TeamMember;

class TeamMemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $teamMembers = [
            // Board Members
            [
                'name' => 'Madanraj Katuwal',
                'position' => 'Chairperson',
                'phone' => '9852830746',
                'email' => 'madanraj.katuwal@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Kamal Bahadur Katuwal',
                'position' => 'Vice-Chairperson',
                'phone' => '9842824042',
                'email' => 'kamal.katuwal@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Madhab Prasad Pokhrel',
                'position' => 'Secretary',
                'phone' => '9842838904',
                'email' => 'madhab.pokharel@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'featured' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Hari Bahadur Basnet',
                'position' => 'Treasurer',
                'phone' => '9842828132',
                'email' => 'hari.basnet@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Sushila Rana Maagar',
                'position' => 'Female Member',
                'phone' => '9842916242',
                'email' => 'shusila.magar@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Mahan Kumari Rai',
                'position' => 'Female Member',
                'phone' => '9842861511',
                'email' => 'mahan.rai@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Uma Katuwal',
                'position' => 'Female Member',
                'phone' => '9845648372',
                'email' => 'uma.katuwal@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Padam Bahadur Sarki',
                'position' => 'Dalit Member',
                'phone' => '9842983656',
                'email' => 'padam.sarki@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Suman Pariyar',
                'position' => 'Dalit Member',
                'phone' => '9815777161',
                'email' => 'suman.pariyar@jidsnepal.org.np',
                'department' => 'Board Member',
                'is_active' => true,
                'sort_order' => 9,
            ],
            
            // Project Office Staff
            [
                'name' => 'Dinesh Chandra Jha',
                'position' => 'Executive Director',
                'phone' => '9852831206',
                'email' => 'dinesh.jha@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'featured' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Pabitra Pariyar',
                'position' => 'Gesu/Admin Officer',
                'phone' => '9842851493',
                'email' => 'pabitra.pariyar@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Hemant Kishwor Mandal',
                'position' => 'MEAL/Admin Officer',
                'phone' => '9814781404',
                'email' => 'hemant.mandal@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Sushil Chandra Jha',
                'position' => 'Admin/Finance Officer',
                'phone' => '9842832817',
                'email' => 'sushil.jha@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Lalita Kumari Chaudhari',
                'position' => 'Logistic Assistant',
                'phone' => '9804791535',
                'email' => 'lalita.chaudhari@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Anjali Kumari Singh',
                'position' => 'Finance Assistant',
                'phone' => '9824707054',
                'email' => 'anjali.singh@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Umesh Kumar Das',
                'position' => 'SOP Project Coordinator',
                'phone' => '9844093864',
                'email' => 'umesh.das@jidsnepal.org.np',
                'department' => 'SOP Project Office',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Subash Chandra Chaudhary',
                'position' => 'FCA Project Coordinator',
                'phone' => '9842878482',
                'email' => 'subash.chaudhary@jidsnepal.org.np',
                'department' => 'FCA Project Office',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Janak Dev Bhatta',
                'position' => 'SOP Field Supervisor',
                'phone' => '9848777934',
                'email' => 'janak.bhatta@jidsnepal.org.np',
                'department' => 'SOP Project Office',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Arjun Prasad Panjiyar',
                'position' => 'MEAL Assistant',
                'phone' => '9816782488',
                'email' => 'arjun.panjiyar@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Hem Raj Adhikari',
                'position' => 'FCA Field Supervisor',
                'phone' => '9846875323',
                'email' => 'hemraj.adhikari@jidsnepal.org.np',
                'department' => 'FCA Project Office',
                'is_active' => true,
                'sort_order' => 20,
            ],
            
            // SOP Mobilizers - East
            [
                'name' => 'Laxmi Kumari Chaudhary',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9815758156',
                'email' => 'laxmi.chaudhari@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Nisha Kumari Sardar',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9814777553',
                'email' => 'nisha.sardar@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Saroj Kumar Chaudhary',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9804739281',
                'email' => 'saroj.chaudhari@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Thaman Bahadur Thapa Magar',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9861807901',
                'email' => 'thaman.magar@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Khadga Bahadur Khatri',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9840146282',
                'email' => 'khadga.khatri@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Santosh Rai',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9861814145',
                'email' => 'santosh.rai@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Dhan Bahadur Magar',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9849388870',
                'email' => 'dhan.magar@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Rita Karki',
                'position' => 'SOP Mobilizer (East)',
                'phone' => '9762856613',
                'email' => 'rita.karki@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 28,
            ],
            
            // SOP Mobilizers - West
            [
                'name' => 'Indra Narayan Shrestha',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9849388870',
                'email' => 'indra.shrestha@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Ashok Kumar Rai',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9819772097',
                'email' => 'ashok.rai@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 30,
            ],
            [
                'name' => 'Bhakta Bahadur Magar',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9842880153',
                'email' => 'bhakta.magar@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Binda Kumari Thapa Magar',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9842898710',
                'email' => 'binda.magar@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 32,
            ],
            [
                'name' => 'Tilaram BK',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9861053075',
                'email' => 'tilaram.bk@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Anjana Rai',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9866826622',
                'email' => 'anjana.rai@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Kamala Kumari Rai',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9863435136',
                'email' => 'kamala.rai@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 35,
            ],
            [
                'name' => 'Pratima Magar',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9861217031',
                'email' => 'pratima.magar@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 36,
            ],
            [
                'name' => 'Sushila Rai',
                'position' => 'SOP Mobilizer (West)',
                'phone' => '9842921501',
                'email' => 'sushila.rai@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 37,
            ],
            
            // Support Staff
            [
                'name' => 'Deepak Kumar Mandal',
                'position' => 'Facilitator',
                'phone' => '9824765352',
                'email' => 'deepak.mandal@jidsnepal.org.np',
                'department' => 'Field Staff',
                'is_active' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'Sanju Kumari Chaudhary',
                'position' => 'Office Assistant',
                'phone' => '9817758156',
                'email' => 'sanju.chaudhary@jidsnepal.org.np',
                'department' => 'SOP Project Office',
                'is_active' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'Ganesh Bahadur Katuwal',
                'position' => 'Driver',
                'phone' => '9842885446',
                'email' => 'ganesh.katuwal@jidsnepal.org.np',
                'department' => 'Project Office',
                'is_active' => true,
                'sort_order' => 40,
            ],
        ];

        foreach ($teamMembers as $member) {
            TeamMember::updateOrCreate(
                ['email' => $member['email']],
                array_merge($member, [
                    'bio' => 'Team member at JIDS Nepal working in ' . $member['department'] . ' as ' . $member['position'] . '.',
                ])
            );
        }
    }
}
